### ISSUE TITLE
😮how to upload pictures to github isseus by shareX ?|如何通过ShareX 自定义上传功能实现上传图片到github issues ？

### ISSUE THREAD

**Issue by geekyouth** [ShareX/CustomUploaders#156]
😮how to upload pictures to github isseus by shareX ?
如何通过ShareX 自定义上传功能实现上传图片到github issues ？

and then response the picture's link : https:xxx  url ?
然后返回https 的图片链接？

how to set ?
如何设置？

![image](https://user-images.githubusercontent.com/12899262/45264388-5fb68700-b46e-11e8-8013-212d9937acad.png)

**Comment by qewc** [comment]
I don't think uploading images straight to GitHub is possible at the moment.

**Comment by geekyouth** [comment]
@qewc 
now i can only upload picture from github web browser！！！that is too trouble！！！
现在只能通过github 网页端实现上传图片，这种方式太麻烦。

![image](https://user-images.githubusercontent.com/12899262/45472335-8cb4b380-b766-11e8-8b0e-cb7d5436e2e8.png)

**Comment by MAGICCC** [comment]
Why would you upload via ShareX to github?

**Comment by tinybarks** [comment]
You cannot automatically upload images to GitHub because it may violate [Terms of Service](https://github.com/site/terms). You should only upload files by using GitHub in a browser. 

If you want to automate adding an image to a comment, upload the image elsewhere.

You can use GitHub API [v3](https://developer.github.com/v3/) (REST) or [v4](https://developer.github.com/v4/) (GraphQL) to add this text to a comment:

```markdown
![alt text](https://example.com/screenshots/1.png)
```
This will embed the image. GitHub does this too if you upload an image.
