### ISSUE TITLE
pixeldrain.com support as a logged-in user

### ISSUE THREAD

**Issue by TreeZenDE** [ShareX/CustomUploaders#296]
Currently pixeldrain.com with CustomUploader is unfortunately only supported as a guest. Therefore the option to delete uploads manually is missing. This option is only available for logged in users.
Is it possible to provide the pixeldrain.com CustomUploader with login?

**Comment by KharmaScribbles** [comment]
@TreeZenDE 

It's a bit of a convaluted processs to do this right now.  I even signed up to figure out how to do it for you but then I got upset and looked to Google, where I found this:

`"Hello! Uploading to personal user accounts through the API is not officially supported yet. I am currently working on this.

What you can do is use the hidden login API:

POST /api/user/login

It expects a username and password in the POST body. You'll get a JSON object back with an API key. You can then put that key in the password field of HTTP Basic auth to use the API from your user account. Good luck!"`  - [reddit][1]

So basically you would need to first get your own API key and then it's an easy edit to your sxcu file. 

So, first you need to get your API key.  I used ShareX's "text upload" test for this.  In your "Custom Uploader Settings:

![text1](https://user-images.githubusercontent.com/36386908/86766155-5dd89300-c007-11ea-9dac-ef643be1a4bd.png)
I've highlighted and pointed to important parts for filling out the request tab. Make sure your request tab looks exactly like mine where I have highlights.. Of course replace your username and password with your own!

 I have a little arrow pointed at "test" tab because that is where you will find your API key after pressing the "Test" button beside "Text upload" on the left, so lets press it:
![apikey](https://user-images.githubusercontent.com/36386908/86766468-cd4e8280-c007-11ea-92fa-fde0ece3128b.png)
The string after "api_key" is, well, your API key! I have obviously blurred mine out here.

I circled the "Test" button only to illustrate this is where we ended up after pressing that button.  You are done with Part 1!  (make sure to copy your API key somewhere!)

Now keep in mind for this next part I did not download the 'official' .sxcu for pixeldrain, I just did it myself.. This worked for me and actually uploaded the below image to Pixeldrain under my account (I can edit and delete), but what I have may not be the same as what you have already in the body.. Bottom line is my example works.

So really all you'll need to do here is a small edit to what you already have in your image upload .sxcu for pixeldrain; The edit is one parameter in the **Header** section.

![part2](https://user-images.githubusercontent.com/36386908/86768263-844bfd80-c00a-11ea-8557-7cb7f3857004.png)


Name= Authorization 
Value=`Basic $base64:USERNAME:API_KEY$`
(So replace USERNAME with **YOUR** pixeldrain username and the API key _you grabbed from part 1_ - **no quotes**!  
Make sure you pay special attention to where all `$` and `:` are used.. and there is a space after the word "Basic"

And nothing should change as far as the **Response** tab goes, but to check I have `https://pixeldrain.com/u/$json:id$` in the URL field and `https://pixeldrain.com/api/file/$json:id$/thumbnail` for Thumbnail.

---

Right now as you can see, it's not feasible to create a sxcu for ShareX yet since there is a personal step everyone would have to take, and I'm not even confident that I explained part 1 good enough for you (that's a dis on me, by the way ;) ) 

Once the official upload via login API is implemented than you could be the one to make the .sxcu ;)

__If you need help with this current method, reply back and I will do my best to help you.  I can't do a lot without your credentials WHICH I DO NOT WANT TO BE RESPONSIBLE FOR! So if you really can't do it my suggestion is to wait until the dev implements API upload officially :)_


[1]: https://www.reddit.com/r/PixelDrain/comments/giy3k1/upload_through_api/frc01n6/

**Comment by goira0** [comment]
> @TreeZenDE
> 
> It's a bit of a convaluted processs to do this right now. I even signed up to figure out how to do it for you but then I got upset and looked to Google, where I found this:
> 
> > `"Hello! Uploading to personal user accounts through the API > is not officially supported yet. I am currently working on this.
> > What you can do is use the hidden login API:
> > POST /api/user/login
> > It expects a username and password in the POST body. You'll > get a JSON object back with an API key. You can then put that > key in the password field of HTTP Basic auth to use the API
> > from your user account. Good luck!"`  - [reddit](https://www.reddit.com/r/PixelDrain/comments/giy3k1/upload_through_api/frc01n6/)
> 
> So basically you would need to first get your own API key and then it's an easy edit to your sxcu file.
> 
> So, first you need to get your API key. I used ShareX's "text upload" test for this. In your "Custom Uploader Settings:
> 
> ![text1](https://user-images.githubusercontent.com/36386908/86766155-5dd89300-c007-11ea-9dac-ef643be1a4bd.png)
> I've highlighted and pointed to important parts for filling out the request tab. Make sure your request tab looks exactly like mine where I have highlights.. Of course replace your username and password with your own!
> 
> I have a little arrow pointed at "test" tab because that is where you will find your API key after pressing the "Test" button beside "Text upload" on the left, so lets press it:
> ![apikey](https://user-images.githubusercontent.com/36386908/86766468-cd4e8280-c007-11ea-92fa-fde0ece3128b.png)
> Make sure you are on the "Result" tab under "Test"
> 
> The string after "api_key" is, well, your API key! I have obviously blurred mine out here.
> 
> I circled the "Test" button only to illustrate this is where we ended up after pressing that button. You are done with Part 1 and can remove everything if we want! (make sure to copy your API key somewhere!)
> 
> Now keep in mind for this next part I did not download the 'official' .sxcu for pixeldrain, I just did it myself.. This worked for me and actually uploaded the below image to Pixeldrain under my account (I can edit and delete), but what I have may not be the same as what you have already in the body.. Bottom line is my example works.
> 
> So really all you'll need to do here is a small edit to what you already have in your image upload .sxcu for pixeldrain; The edit is one parameter in the **Header** section.
> 
> ![part2](https://user-images.githubusercontent.com/36386908/86768263-844bfd80-c00a-11ea-8557-7cb7f3857004.png)
> 
> > Name= Authorization
> > Value=`Basic $base64:USERNAME:API_KEY$`
> 
> (So replace USERNAME with **YOUR** pixeldrain username and the API key _you grabbed from part 1_ - **no quotes**!
> Make sure you pay special attention to where all `$` and `:` are used.. and there is a space after the word "Basic"
> 
> And nothing should change as far as the **Response** tab goes, but to check I have `https://pixeldrain.com/u/$json:id$` in the URL field and `https://pixeldrain.com/api/file/$json:id$/thumbnail` for Thumbnail.
> 
> Right now as you can see, it's not feasible to create a sxcu for ShareX yet since there is a personal step everyone would have to take, and I'm not even confident that I explained part 1 good enough for you (that's a dis on me, by the way ;) )
> 
> Once the official upload via login API is implemented than you could be the one to make the .sxcu ;)
> 
> _If you need help with this current method, reply back and I will do my best to help you. I can't do a lot without your credentials **WHICH I DO NOT WANT TO BE RESPONSIBLE FOR!** So if you really can't do it my suggestion is to wait until the dev implements API upload officially :)_

@KharmaScribbles 

works perfectly. Thanks!

Can you make a tutorial for 1fichier custom upload? 1fichier supports api.

**Comment by Fornax96** [comment]
Hi. I would like to support this on pixeldrain itself. Does someone have a custom uploader config which which works with authentication (please remove your own key)? Then I can make a download button on pixeldrain which automatically adds the right auth key.

I use Linux so I can't configure it myself. I tried running ShareX Portable in Wine, but it crashes when I open the settings menu.

**Comment by Fornax96** [comment]
I installed ShareX in GNOME Boxes to get this working. You can now download a personalized ShareX uploader from here: https://pixeldrain.com/apps
